apiVersion: v1
kind: Service
metadata:
  name: {{ include "fiware-iota-lorawan.fullname" . }}
  labels:
    {{- include "fiware-iota-lorawan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fiware-iota-lorawan.selectorLabels" . | nindent 4 }}
