apiVersion: v1
kind: Service
metadata:
  name: "{{ include "villas.fullname" . }}-broker"
  labels:
    app.kubernetes.io/component: broker
    {{- include "villas.labels" . | nindent 4 }}
spec:
  ports:
  - name: web-admin
    port: 8083
    targetPort: 15672
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: mqtt
    port: 1883
    targetPort: 1883
  selector:
    app.kubernetes.io/component: broker
