{{ if .Values.controller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-controller"
  labels:
    app.kubernetes.io/component: controller
    {{- include "villas.labels" . | nindent 4 }}
data:
{{- $cfg := .Values.controller.config -}}
{{- $cfg := mergeOverwrite $cfg (dict "components" (concat $cfg.components .Values.controller.extraComponents)) }}
  controller.json: |
{{ toPrettyJson $cfg | indent 4 }}
{{ end }}
