{{ if .Values.controller.enabled }}
{{- $uuid := include "villas.uuid" (dict "global" . "component" "controller") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-controller"
  labels:
    app.kubernetes.io/component: controller
    {{- include "villas.labels" . | nindent 4 }}
{{- with .Values.controller -}}
{{- $comps := list (include "villas.controller.component" (set . "uuid" $uuid) | fromYaml) -}}
{{- $comps := concat $comps .extraConfig.components -}}
{{- $comps := concat $comps .extraComponents -}}
{{- $config := .extraConfig -}}
{{- $config := set $config "components" $comps }}
data:
  uuid: {{ $uuid }}
  controller.json: |
{{ toPrettyJson $config | indent 4 }}
{{ end }}
{{ end }}
