{{ if .Values.controller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-controller"
  labels:
    app.kubernetes.io/component: controller
    {{- include "villas.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
    spec:
      containers:
      - name: controller
        image: {{ .Values.controller.image }}
        imagePullPolicy: Always
        # command: [ ]
        args: [
          "-b", "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@{{ include "villas.fullname" . }}-broker/%2F",
          "-c", "/etc/villas/controller.json", "daemon"
        ]
        volumeMounts:
        - mountPath: /etc/villas/
          name: config
        env:
        - name: RABBITMQ_USERNAME
          value: "{{ .Values.broker.auth.username }}"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "broker.secretName" . }}
              key: rabbitmq-password
      volumes:
      - name: config
        configMap:
          name: "{{ include "villas.fullname" . }}-controller"
{{ end }}
