{{ if .Values.controller.enabled }}
{{- $uuid := (include "villas.uuid" (dict "global" . "component" "controller")) -}}
{{- $_ := set .Values.controller "uuid" $uuid -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-controller"
  labels:
    app.kubernetes.io/component: controller
    {{- include "villas.labels" . | nindent 4 }}
{{- $comps := list (include "villas.controller.component" . | fromYaml) -}}
{{- $comps := concat $comps .Values.controller.extraConfig.components -}}
{{- $comps := concat $comps .Values.controller.extraComponents -}}
{{- $config := .Values.controller.extraConfig -}}
{{- $config := set $config "components" $comps }}
data:
  uuid: {{ .Values.controller.uuid }}
  controller.yaml: |
{{ $config | toYaml | indent 4 }}
{{ end }}
