{{ if .Values.controller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-controller"
  labels:
    app.kubernetes.io/component: controller
    {{- include "villas.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      {{- include "villas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/controller-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/component: controller
        {{- include "villas.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ include "villas.fullname" . }}-controller"
      containers:
      - name: controller
        image: {{ .Values.controller.image }}
        imagePullPolicy: Always
        # command: [ ]
        args: [
          "-b", "amqp://$(AMQP_USER):$(AMQP_PASS)@$(AMQP_HOST)/%2F",
          "-c", "/etc/villas/controller.json", "daemon"
        ]
        volumeMounts:
        - mountPath: /etc/villas/
          name: config
        env:
{{- if .Values.broker.enabled }}
        - name: AMQP_USER
          value: {{ .Values.broker.auth.username | quote }}
        - name: AMQP_HOST
          value: "{{ include "villas.fullname" . }}-broker"
        - name: AMQP_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "broker.secretName" . }}
              key: rabbitmq-password
{{- else }}
        - name: AMQP_USER
          value: {{ .Values.broker.external.username | quote }}
        - name: AMQP_HOST
          value: {{ .Values.broker.external.hostname | quote }}
        - name: AMQP_PASS
          value: {{ .Values.broker.external.password | quote }}
{{- end }}
      volumes:
      - name: config
        configMap:
          name: "{{ include "villas.fullname" . }}-controller"
{{ end }}
