{{ if .Values.controller.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "villas.controller.kubernetes.namespace" . }}
  labels:
    app.kubernetes.io/component: controller
    {{- include "villas.labels" . | nindent 4 }}
{{ end }}
