apiVersion: v1
kind: Service
metadata:
  name: "{{ include "villas.fullname" . }}-frontend"
  labels:
    app.kubernetes.io/component: frontend
    {{- include "villas.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/component: frontend
