{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ include "villas.fullname" . }}"
  labels:
    {{- include "villas.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if .Values.ingress.annotations }}
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
{{- if .Values.web.enabled }}
      - path: /.*
        pathType: ImplementationSpecific
        backend:
          serviceName: "{{ include "villas.fullname" . }}-web-frontend"
          servicePort: http
      - path: /(static/.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: "{{ include "villas.fullname" . }}-web-frontend"
          servicePort: http
      - path: /(api/.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: "{{ include "villas.fullname" . }}-web-backend"
          servicePort: http
      - path: /(swagger/.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: "{{ include "villas.fullname" . }}-web-backend"
          servicePort: http
{{- end }}
      - path: /(rabbitmq/.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: "{{ include "villas.fullname" . }}-broker"
          servicePort: http-stats
{{- if .Values.relay.enabled }}
      - path: /ws/relay/(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: "{{ include "villas.fullname" . }}-relay"
          servicePort: http
{{- end }}
{{- if .Values.node.enabled }}
      - path: /ws/(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: "{{ include "villas.fullname" . }}-node"
          servicePort: http
      - path: /mockup/(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: "{{ include "villas.fullname" . }}-node"
          servicePort: http
{{- end }}
{{- else }}
{{ "The VILLASframework currently can not function without an ingress controller" | fail }}
{{- end }}
