{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "villas.fullname" . }}-demo"
  labels:
    {{- include "villas.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    eonerc.rwth-aachen.de/description: VILLASweb
    eonerc.rwth-aachen.de/link: https://git.rwth-aachen.de/acs/public/villas/web
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: villas.k8s.eonerc.rwth-aachen.de
    http:
      paths:
      - backend:
          serviceName: frontend-
          servicePort: http
        path: /.*
        pathType: ImplementationSpecific
      - backend:
          serviceName: frontend
          servicePort: http
        path: /(static/.*)
        pathType: ImplementationSpecific
      - backend:
          serviceName: backend
          servicePort: http
        path: /(api/.*)
        pathType: ImplementationSpecific
      - backend:
          serviceName: broker
          servicePort: web-admin
        path: /(rabbitmq/.*)
        pathType: ImplementationSpecific
      - backend:
          serviceName: backend
          servicePort: http
        path: /(swagger/.*)
        pathType: ImplementationSpecific
      - backend:
          serviceName: relay
          servicePort: http
        path: /ws/relay/(.*)
        pathType: ImplementationSpecific
      - backend:
          serviceName: node
          servicePort: http
        path: /ws/(.*)
        pathType: ImplementationSpecific
      - backend:
          serviceName: node
          servicePort: http
        path: /mockup/(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - villas.k8s.eonerc.rwth-aachen.de
    secretName: letsencrypt-prod-villas-demo
{{- end }}
