{{ if .Values.node.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-node"
  labels:
    {{- include "villas.labels" . | nindent 4 }}
data:
{{- $cfg := .Values.node.config -}}
{{- $cfg := mergeOverwrite $cfg (dict "nodes" .Values.node.extraNodes) -}}
{{- $cfg := mergeOverwrite $cfg (dict "paths" (concat .Values.node.config.paths .Values.node.extraPaths)) }}
  node.json: |
{{ toPrettyJson $cfg | indent 4 }}
  controller.json: |
    {
      "components": [
        {
          "name": "VILLASnode",
          "category": "controller",
          "type": "villas-node",
          "api_url": "http://localhost:8080"
        }
      ]
    }
{{ end }}
