{{ if .Values.node.enabled }}
{{- $uuid := include "villas.uuid" (dict "global" . "component" "node") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-node"
  labels:
    {{- include "villas.labels" . | nindent 4 }}
data:
  uuid: {{ $uuid }}
{{- $config := .Values.node.extraConfig -}}
{{- $config := set $config "uuid" $uuid -}}
{{- $config := set $config "nodes" (mergeOverwrite $config.nodes .Values.node.extraNodes) -}}
{{- $config := set $config "paths" (concat         $config.paths .Values.node.extraPaths) }}
  node.json: |
{{ toPrettyJson $config | indent 4 }}
  controller.json: |
    {
      "components": [
        {
          "name": "VILLASnode",
          "category": "controller",
          "type": "villas-node",
          "api_url": "http://localhost:8080"
        }
      ]
    }
{{ end }}
