{{ if .Values.node.enabled }}
{{- $uuid := include "villas.uuid" (list . "node") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-node"
  labels:
    {{- include "villas.labels" . | nindent 4 }}
data:
  uuid: {{ $uuid }}
{{- $config := .Values.node.extraConfig -}}
{{- $_ := set $config "uuid" $uuid -}}
{{- $_ := set $config "nodes" (mergeOverwrite $config.nodes .Values.node.extraNodes) -}}
{{- $_ := set $config "paths" (concat         $config.paths .Values.node.extraPaths) }}
  node.json: |
{{ $config | toPrettyJson | indent 4 }}
{{ end }}
