{{ if .Values.node.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-node"
  labels:
    app.kubernetes.io/component: node
    {{- include "villas.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: node
      {{- include "villas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/node-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/component: node
        {{- include "villas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: node
        args: [ "node", "-d", {{ .Values.node.logLevel | quote }}, "/etc/villas/node.json" ]
        image: {{ .Values.node.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
{{ $start := int .Values.node.portOffset }}
{{ $count := int .Values.node.portCount }}
{{ $end := int (add $start $count) }}
{{ range untilStep $start $end 1 }}
        - containerPort: {{ . }}
          protocol: UDP
{{ end }}
        env:
        - name: UUID
          valueFrom:
            configMapKeyRef:
              name: "{{ include "villas.fullname" . }}-node"
              key: uuid
        volumeMounts:
        - mountPath: /etc/villas/
          name: config
{{- if .Values.node.persistence.enabled }}
        - mountPath: /data
          name: data
{{- end }}
        livenessProbe:
          httpGet:
            path: /api/v2/capabilities
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: "{{ include "villas.fullname" . }}-node"
{{- if .Values.node.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: "{{ include "villas.fullname" . }}-node-data"
{{- end }}
{{- end }}
