apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "villas.fullname" . }}-node-data"
  labels:
    app.kubernetes.io/component: node-claim1
    {{- include "villas.labels" . | nindent 4 }}
spec:
  storageClassName: "{{ .Values.storageClass }}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
