{{ if .Values.node.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-node"
  labels:
    app.kubernetes.io/component: node
    {{- include "villas.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: node
  template:
    metadata:
      labels:
        app.kubernetes.io/component: node
    spec:
      containers:
      - name: node
        args: [ "node", "/etc/villas/node.json" ]
        image: {{ .Values.node.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
{{ $start := int .Values.node.portOffset }}
{{ $count := int .Values.node.portCount }}
{{ $end := int (add $start $count) }}
{{ range untilStep $start $end 1 }}
        - containerPort: {{ . }}
          protocol: UDP
{{ end }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/villas/
          name: config
        - mountPath: /data
          name: data
        livenessProbe:
          httpGet:
            path: /api/v2/capabilities
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: controller
        image: {{ .Values.controller.image }}
        imagePullPolicy: Always
        args: [
          "-b", "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@{{ include "villas.fullname" . }}-broker/%2F",
          "-c", "/etc/villas/controller.json", "daemon"
        ]
        volumeMounts:
        - mountPath: /etc/villas/
          name: config
        env:
        - name: RABBITMQ_USERNAME
          value: "{{ .Values.broker.auth.username }}"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "broker.secretName" . }}
              key: rabbitmq-password
      volumes:
      - name: config
        configMap:
          name: "{{ include "villas.fullname" . }}-node"
      - name: data
        persistentVolumeClaim:
          claimName: "{{ include "villas.fullname" . }}-node-data"
{{ end }}
