apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-node-config"
  labels:
    {{- include "villas.labels" . | nindent 4 }}
data:
  demo.conf: |-
{{ (.Files.Glob "etc/villas/node/*").AsConfig | indent 2 }}
