{{ if .Values.pintura.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-pintura"
  labels:
    app.kubernetes.io/component: pintura
    {{ include "villas.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pintura.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: pintura
      {{- include "villas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pintura
        {{- include "villas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.pintura.image }}
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
{{ end }}
