{{ if .Values.pintura.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "villas.fullname" . }}-pintura"
  labels:
    app.kubernetes.io/component: pintura
    {{- include "villas.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/component: pintura
    {{- include "villas.selectorLabels" . | nindent 4 }}
{{ end }}
