{{ if .Values.web.auth.external.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-proxy"
  labels:
    app.kubernetes.io/component: proxy
    {{- include "villas.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: proxy
      {{- include "villas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: proxy
        {{- include "villas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: proxy
        image: {{ .Values.proxy.image }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 4180
        env:
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: ":4180"
        - name: OAUTH2_PROXY_UPSTREAMS
          value: "http://{{ include "villas.fullname" . }}-web-backend"
        - name: OAUTH2_PROXY_CLIENT_ID
          value: {{ .Values.web.auth.external.client_id | quote }}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: {{ .Values.web.auth.external.client_secret | quote }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: {{ .Values.web.auth.external.cookie_secret }}
        - name: OAUTH2_PROXY_LOGIN_URL
          value: {{ .Values.web.auth.external.login_url | quote }}
        - name: OAUTH2_PROXY_REDEEM_URL
          value: {{ .Values.web.auth.external.redeem_url | quote }}
        - name: OAUTH2_PROXY_VALIDATE_URL
          value: {{ .Values.web.auth.external.validate_url | quote }}
        - name: OAUTH2_PROXY_REVERSE_PROXY
          value: "true"
        - name: OAUTH2_PROXY_SET_XAUTHREQUEST
          value: "true"
        - name: OAUTH2_PASS_ACCESS_TOKEN
          value: "true"
        - name: OAUTH2_PROXY_PROVIDER
          value: {{ .Values.web.auth.external.provider | quote }}
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: "true"
{{- if .Values.web.auth.external.email_domains }}
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: {{ .Values.web.auth.external.email_domains | join "," | quote }}
{{- else }}
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: "*"
{{- end }}
{{- if .Values.web.auth.external.allowed_groups }}
        - name: OAUTH2_PROXY_ALLOWED_GROUPS
          value: {{ .Values.web.auth.external.allowed_groups | join "," | quote }}
{{- end }}
{{- range $key, $value := .Values.proxy.extraEnv }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 3
          periodSeconds: 3
{{- end }}
