apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-relay"
  labels:
    app.kubernetes.io/component: relay
    {{- include "villas.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: relay
  template:
    metadata:
      labels:
        app.kubernetes.io/component: relay
    spec:
      containers:
      - args:
        - relay
        image: registry.git.rwth-aachen.de/acs/public/villas/node:demo-v0.3
				imagePullPolicy: Always
        name: relay
        securityContext:
          privileged: true
        ports:
        - name: http
          containerPort: 8088
        livenessProbe:
          httpGet:
            path: /api/v1
            port: 8088
          initialDelaySeconds: 3
          periodSeconds: 3
