{{ if .Values.relay.enabled }}
{{- $uuid := include "villas.uuid" (list . "relay") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-relay"
  labels:
    {{- include "villas.labels" . | nindent 4 }}
data:
  uuid: {{ $uuid }}
{{ end }}
