{{ if .Values.relay.enabled }}
{{- $uuid := include "villas.uuid" (dict "global" . "component" "relay") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-relay"
  labels:
    {{- include "villas.labels" . | nindent 4 }}
data:
  uuid: {{ $uuid }}
  controller.json: |
    {
      "components": [
        {
          "name": "VILLASrelay",
          "category": "controller",
          "type": "villas-relay",
          "api_url": "http://localhost:8088"
        }
      ]
    }
{{ end }}
