{{- define "villas.relay.config.controller" }}
components:
- name: VILLASrelay
  category: manager
  type: villas-relay
  api_url: http://localhost:8088
{{- if .Values.ingress.enabled }}
  api_url_external: {{include "villas.baseurl" . }}/ws/relay
{{- end }}
{{- end }}

{{ if .Values.relay.enabled }}
{{- $uuid := include "villas.uuid" (dict "global" . "component" "relay") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-relay"
  labels:
    {{- include "villas.labels" . | nindent 4 }}
data:
  uuid: {{ $uuid }}
  controller.yaml: |
{{ include "villas.relay.config.controller" . | indent 4 }}
{{ end }}
