{{ if .Values.relay.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-relay"
  labels:
    app.kubernetes.io/component: relay
    {{- include "villas.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: relay
  template:
    metadata:
      labels:
        app.kubernetes.io/component: relay
    spec:
      containers:
      - name: relay
        args:
        - relay
        image: {{ .Values.relay.image }}
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - name: http
          containerPort: 8088
        livenessProbe:
          httpGet:
            path: /api/v1
            port: 8088
          initialDelaySeconds: 3
          periodSeconds: 3
      - name: controller
        image: {{ .Values.controller.image }}
        imagePullPolicy: Always
        command: [ "villas-controller" ]
        args: [
          "-b", "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@{{ include "villas.fullname" . }}-broker/%2F",
          "-c", "/etc/villas/controller.json", "daemon"
        ]
        volumeMounts:
        - mountPath: /etc/villas/
          name: config
        env:
        - name: RABBITMQ_USERNAME
          value: "{{ .Values.broker.auth.username }}"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "broker.secretName" . }}
              key: rabbitmq-password
      volumes:
      - name: config
        configMap:
          name: "{{ include "villas.fullname" . }}-relay"
{{ end }}
