{{ if .Values.relay.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-relay"
  labels:
    app.kubernetes.io/component: relay
    {{- include "villas.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: relay
      {{- include "villas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: relay
        {{- include "villas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: relay
        args: [
          "relay", "-u", "$(UUID)", "-d", "{{ .Values.relay.logLevel }}"
        ]
        image: {{ .Values.relay.image }}
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - name: http
          containerPort: 8088
        env:
        - name: UUID
          valueFrom:
            configMapKeyRef:
              name: "{{ include "villas.fullname" . }}-relay"
              key: uuid
        livenessProbe:
          httpGet:
            path: /api/v1
            port: 8088
          initialDelaySeconds: 3
          periodSeconds: 3
      - name: controller
        image: {{ .Values.controller.image }}
        imagePullPolicy: Always
        command: [ "villas-controller" ]
        args: [
          "-b", "amqp://$(AMQP_USER):$(AMQP_PASS)@$(AMQP_HOST)/%2F",
          "-c", "/etc/villas/controller.json", "daemon"
        ]
        volumeMounts:
        - mountPath: /etc/villas/
          name: config
        env:
{{- if .Values.broker.enabled }}
        - name: AMQP_USER
          value: "{{ .Values.broker.auth.username }}"
        - name: AMQP_HOST
          value: "{{ include "villas.fullname" . }}-broker"
        - name: AMQP_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "broker.secretName" . }}
              key: rabbitmq-password
{{- else }}
        - name: AMQP_USER
          value: "{{ .Values.broker.external.username }}"
        - name: AMQP_HOST
          value: "{{ .Values.broker.external.hostname }}"
        - name: AMQP_PASS
          value: "{{ .Values.broker.external.password }}"
{{- end }}
      volumes:
      - name: config
        configMap:
          name: "{{ include "villas.fullname" . }}-relay"
{{ end }}
