{{- define "villas.web.config" }}
mode: {{ .Values.web.mode }}
port: 4000
base:
  host: {{ .Values.ingress.host }}
admin:
  user: {{ .Values.web.admin.username }}
  mail: {{ .Values.web.admin.mail }}
amqp:
{{- if .Values.broker.enabled }}
  host: {{ include "villas.fullname" . }}-broker/%2F
  user: {{ .Values.broker.auth.username }}
{{- else }}
  host: {{ .Values.broker.external.hostname }}
  user: {{ .Values.broker.external.username }}
{{- end }}
db:
{{- if .Values.database.enabled }}
  name: {{ .Values.database.postgresqlDatabase }}
  host: {{ include "villas.fullname" . }}-database
  user: {{ .Values.database.postgresqlUsername }}
{{- else }}
  name: {{ .Values.database.external.name }}
  host: {{ .Values.database.external.hostname }}
  user: {{ .Values.database.external.username }}
{{- end }}
{{- if .Values.s3.enabled }}
s3:
{{- if .Values.s3.external.enabled }}
  bucket: {{ .Values.s3.external.bucket }}
  region: {{ .Values.s3.external.region }}
  endpoint: {{ .Values.s3.external.endpoint }}
  nossl: {{ .Values.s3.external.nossl }}
  pathstyle: {{ .Values.s3.external.pathstyle }}
{{- else }}
  bucket: {{ get (.Values.s3.buckets | first) "name" }}
  region: default
  endpoint: {{ include "villas.fullname" . }}-s3:9000
  nossl: true
  pathstyle: true
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.web.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-web"
  labels: {{ include "villas.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toPrettyJson (mergeOverwrite (include "villas.web.config" . | fromYaml) .Values.web.extraConfig) | indent 4 }}
{{ end }}
