{{ if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-web-backend"
  labels:
    app.kubernetes.io/component: web-backend
    {{- include "villas.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: web-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web-backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: kubernetes-worker-7
      imagePullSecrets:
      - name: stvogel-rwth-pull-secret
      containers:
      - name: backend
        image: {{ .Values.web.backend.image }}
        imagePullPolicy: Always
        command: [ "villasweb-backend" ]
        env:
        - name: MODE
          value: release
        - name: BASE_HOST
          value: "{{ .Values.ingress.host }}"
        - name: DB_NAME
          value: {{ .Values.database.postgresqlDatabase }}
        - name: DB_HOST
          value: {{ include "villas.fullname" . }}-database
        - name: DB_USER
          value: "{{ .Values.database.postgresqlUsername }}"
        - name: DB_PASS
          value: "{{ .Values.database.postgresqlPassword }}"
        - name: AMQP_HOST
          value: {{ include "villas.fullname" . }}-broker/%2F
        - name: AMQP_USER
          value: "{{ .Values.broker.auth.username }}"
        - name: AMQP_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "broker.secretName" . }}
              key: rabbitmq-password
        livenessProbe:
          httpGet:
            path: /api/v2/healthz
            port: 4000
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - name: http
          containerPort: 4000
{{ end }}
