{{ if and .Values.web.enabled .Values.web.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "villas.fullname" . }}-web
  labels:
    {{- include "villas.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.web.auth.admin.password | default (randAlphaNum 10) | b64enc | quote }}
{{ end }}
