{{- define "villas.web.config" }}
mode: {{ .Values.web.mode | quote }}
title: {{ .Values.web.title | quote }}
sub_title: {{ .Values.web.sub_title | quote }}
contact:
  name: {{ .Values.web.contact.name | quote }}
  mail: {{ .Values.web.contact.mail | quote }}
port: 4000
base:
  host: {{ .Values.ingress.host }}
admin:
  user: {{ .Values.web.auth.admin.username }}
  mail: {{ .Values.web.auth.admin.mail }}
amqp:
{{- if .Values.broker.enabled }}
  host: {{ include "villas.fullname" . }}-broker/%2F
  user: {{ .Values.broker.auth.username }}
{{- else }}
  host: {{ .Values.broker.external.hostname }}
  user: {{ .Values.broker.external.username }}
{{- end }}
db:
{{- if .Values.database.enabled }}
  name: {{ .Values.database.postgresqlDatabase }}
  host: {{ include "villas.fullname" . }}-database
  user: {{ .Values.database.postgresqlUsername }}
{{- else }}
  name: {{ .Values.database.external.name }}
  host: {{ .Values.database.external.hostname }}
  user: {{ .Values.database.external.username }}
{{- end }}
{{- if .Values.s3.enabled }}
s3:
  bucket: {{ .Values.s3.bucket }}
  region: {{ .Values.s3.region }}
{{- if .Values.s3.external.enabled }}
  endpoint: {{ .Values.s3.external.endpoint }}
  nossl: {{ .Values.s3.external.nossl }}
  pathstyle: {{ .Values.s3.external.pathstyle }}
{{- else }}
  endpoint: {{ include "villas.s3.endpoint" . }}
  nossl: {{ not .Values.ingress.tls.enabled }}
  pathstyle: true
{{- end }}
{{- end }}
{{- if .Values.web.auth.external.enabled }}
auth:
  external: true
  provider_name: {{ .Values.web.auth.provider_name | quote }}
  logout_url: {{ .Values.web.auth.logout_url | quote }}
{{- end }}
{{- end }}

{{- if .Values.web.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "villas.fullname" . }}-web"
  labels: {{ include "villas.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ mergeOverwrite (include "villas.web.config" . | fromYaml) .Values.web.extraConfig | toYaml | indent 4 }}
{{ end }}
