{{ if and .Values.web.enabled .Values.web.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "villas.fullname" . }}-web-backend"
  labels:
    app.kubernetes.io/component: web-backend
    {{- include "villas.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: web-backend
      {{- include "villas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web-backend
        {{- include "villas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: backend
        image: {{ .Values.web.backend.image }}
        imagePullPolicy: Always
        command: [ "villasweb-backend" ]
        args: [ "-config", "/etc/villas/config.yaml" ]
        env:
{{- if .Values.s3.enabled }}
        - name: AWS_ACCESS_KEY_ID
{{- if .Values.s3.external.enabled }}
          value: {{ .Values.s3.external.access_key }}
{{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ template "s3.secretName" . }}
              key: accesskey
{{- end }}
        - name: AWS_SECRET_ACCESS_KEY
{{- if .Values.s3.external.enabled }}
          value: {{ .Values.s3.external.secret_key }}
{{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ template "s3.secretName" . }}
              key: secretkey
{{- end }}
{{- end }}
        - name: DB_PASS
{{- if .Values.database.enabled }}
          valueFrom:
            secretKeyRef:
              name: {{ include "database.secretName" . }}
              key: postgresql-password
{{- else }}
          value: {{ .Values.database.external.password | quote }}
{{- end }}
        - name: AMQP_PASS
{{- if .Values.broker.enabled }}
          valueFrom:
            secretKeyRef:
              name: {{ include "broker.secretName" . }}
              key: rabbitmq-password
{{- else }}
          value: {{ .Values.broker.external.password | quote }}
{{- end }}
        - name: ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "villas.fullname" . }}-web
              key: password
        livenessProbe:
          httpGet:
            path: /api/v2/healthz
            port: 4000
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - name: http
          containerPort: 4000
        volumeMounts:
        - mountPath: /etc/villas/
          name: config
      volumes:
      - name: config
        configMap:
          name: "{{ include "villas.fullname" . }}-web"
{{ end }}
