{{ if and .Values.web.enabled .Values.web.backend.enabled }}
{{- $secretName := include "villas.fullname" . | printf "%s-web" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  labels:
    {{- include "villas.labels" . | nindent 4 }}
type: Opaque
{{- if $secret }}
data: {{ $secret.data | toYaml | nindent 2 }}
{{ else }}
data:
  password: {{ .Values.web.admin.password | default (randAlphaNum 10) | b64enc | quote }}
{{ end }}
{{ end }}
