{{ if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "villas.fullname" . }}-web-backend"
  labels:
    app.kubernetes.io/component: backend
    {{- include "villas.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '4000'
    prometheus.io/path: '/metrics'
spec:
  ports:
  - name: http
    port: 4000
    targetPort: 4000
  selector:
    app.kubernetes.io/component: web-backend
{{ end }}
