apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mongo-express
    app.kubernetes.io/part-of: villas-web
  name: mongo-express
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: mongo-express
      app.kubernetes.io/part-of: villas-web
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mongo-express
        app.kubernetes.io/part-of: villas-web
    spec:
      containers:
      - image: mongo-express:0.49.0
        name: mongo-express
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: password
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: password
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: username
        - name: ME_CONFIG_MONGODB_SERVER
          value: database
        - name: ME_CONFIG_SITE_BASEURL
          value: /mongo-express/
        ports:
        - containerPort: 8081
          name: http
