apiVersion: v2
name: villas
description: A Helm chart for the VILLASframework

icon: https://packages.fein-aachen.org/helm/icons/villas_framework.png

type: application

version: 0.13.0
appVersion: 1.18.3

maintainers:
  - name: Steffen Vogel
    email: post@steffenvogel.de
    url: https://www.steffenvogel.de

dependencies:
  - name: rabbitmq
    version: 10.3.6
    repository: "https://charts.bitnami.com/bitnami"
    condition: "broker.enabled"
    alias: broker

  - name: postgresql
    version: 11.9.1
    repository: "https://charts.bitnami.com/bitnami"
    condition: "database.enabled"
    alias: database

  - name: minio
    version: 11.10.3
    repository: https://charts.bitnami.com/bitnami
    condition: "s3.enabled"
    alias: s3
