apiVersion: v2
name: villas
description: A Helm chart for the VILLASframework

icon: https://packages.fein-aachen.org/helm/icons/villas_framework.png

type: application

version: 0.9.1
appVersion: 1.18.3

maintainers:
- name: Steffen Vogel
  email: svogel2@eonerc.rwth-aachen.de
  url: https://www.steffenvogel.de

dependencies:
- name: rabbitmq
  version: "7.8.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: "broker.enabled"
  alias: broker

- name: postgresql
  version: "9.8.11"
  repository: "https://charts.bitnami.com/bitnami"
  condition: "database.enabled"
  alias: database

- name: minio
  version: 8.0.9
  repository: https://helm.min.io/
  condition: "s3.enabled"
  alias: s3
