imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

storageClass: null

ingress:
  enabled: true

  host: localhost

  annotations: {}

  tls:
    enabled: false
    secretName: villas-tls

web:
  enabled: true

  mode: release
  title: VILLASweb
  sub_title: ""
  contact:
    name: Steffen Vogel
    mail: svogel2@eonerc.rwth-aachen.de

  metrics:
    enabled: true

  extraConfig: {}

  auth:
    logout_url: /oauth2/sign_out?rd=https%3A%2F%2Fjupyter.k8s.eonerc.rwth-aachen.de%2Fhub%2Flogout

    admin:
      username: admin
      mail: admin@example.com
      # password: changeme

    external:
      enabled: false

      client_id: villas
      client_secret: "Ho0Zeilahxoh3Cae0ao9rieHooL1oonah0nash6aiNae7phaiceeCoo9Eesh6tei"

      cookie_secret: "ohth8iin6QuiequeGu5tiengizip4eid"

      # email_domains:
      # - "*"
      # allowed_groups:
      # - student

      provider: jupyterhub
      provider_name: JupyterHub

      login_url: https://jupyter.k8s.eonerc.rwth-aachen.de/hub/api/oauth2/authorize
      redeem_url: https://jupyter.k8s.eonerc.rwth-aachen.de/hub/api/oauth2/token
      validate_url: https://jupyter.k8s.eonerc.rwth-aachen.de/hub/api/oauth2/validate

  backend:
    enabled: true

    image: registry.git.rwth-aachen.de/acs/public/villas/web-backend-go:master

  #   external:
  #     host: host.minikube.internal
  #     ip: 192.168.64.1
  #     port: 4000

  frontend:
    enabled: true

    image: registry.git.rwth-aachen.de/acs/public/villas/web:master
    replicas: 1

proxy:
  image: quay.io/oauth2-proxy/oauth2-proxy

  extraEnv:
    OAUTH2_PROXY_JUPYTERHUB_URL: https://jupyter.k8s.eonerc.rwth-aachen.de

node:
  enabled: true

  image: registry.git.rwth-aachen.de/acs/public/villas/node:latest

  uuid: null # Autogenerate UUID
  logLevel: info

  portOffset: 12000
  portCount: 10

  persistence:
    enabled: true
    size: 1Gi

  extraConfig:
    hugepages: 0

    http:
      htdocs: /usr/share/villas/node/web
      port: 8080

    logging:
      level: info

    nodes:
      sig:
        type: signal
        signal: mixed
        values: 5
        rate: 20
      lo:
        type: loopback

      ws_sig:
        type: websocket
        in:
          signals: []
      ws_lo:
        type: websocket
        in:
          signals:
          - name: Loopback
            type: float

    paths:
    - in: sig
      out: ws_sig
    - in: ws_lo
      out: lo
    - in: lo
      out: ws_lo

  extraNodes: {}
  extraPaths: []

relay:
  enabled: true

  uuid: null # Autogenerate UUID
  logLevel: info
  loopback: false

  image: registry.git.rwth-aachen.de/acs/public/villas/node:latest

controller:
  enabled: true

  rbac:
    enabled: true

  uuid: null # Autogenerate UUID
  namespace: null # Use "{{ .Release.Namespace }}-controller"
  logLevel: info
  name: Kubernetes Controller

  image: registry.git.rwth-aachen.de/acs/public/villas/controller:latest

  extraComponents: []

  extraConfig:
    components: []

database:
  # Set to false for using an external broker
  # If so, provide the connection details in broker.external
  enabled: true

  # external:
  #   hostname: postgresql.postgresql
  #   name: villas
  #   username: villas
  #   password: XXXX

  postgresqlUsername: villas
  postgresqlDatabase: villas
  postgresqlPassword: changeme

broker:
  # Set to false for using an external broker
  # If so, provide the connection details in broker.external
  enabled: true

  # external:
  #   hostname: broker.villas-demo
  #   username: admin
  #   password: changeme

  extraPlugins: rabbitmq_mqtt

  service:
    extraPorts:
    - name: mqtt
      port: 1883
      targetPort: mqtt

  auth:
    username: villas
    # password: changeme
    # erlangCookie: Uy2RmPBj66F7fTZ8Bx66eKb1xOOoZTyv

s3:
  enabled: true

  bucket: villas-web
  region: default

  external:
    enabled: false

    access_key: changeme
    secret_key: changeme

    endpoint: minio.minio

    nossl: true
    pathstyle: true

  accessKey: changeme
  secretKey: changeme

  buckets:
  - name: villas-web
    policy: none
    purge: false

  resources:
    requests:
      # default is 4Gi which is to big for most dev machines...
      memory: 1Gi

  environment:
    MINIO_REGION_NAME: default
    MINIO_BROWSER: off

