imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

storageClass: null

ingress:
  enabled: true

  host: localhost

  annotations: {}

  tls:
    enabled: false
    secretName: villas-tls

web:
  enabled: true

  metrics:
    enabled: true

  mode: release

  extraConfig: {}

  admin:
    username: admin
    mail: admin@example.com

  backend:
    enabled: true

    image: registry.git.rwth-aachen.de/acs/public/villas/web-backend-go:e3af6dc8

  #   external:
  #     host: host.minikube.internal
  #     ip: 192.168.64.1
  #     port: 4000

  frontend:
    enabled: true

    image: registry.git.rwth-aachen.de/acs/public/villas/web:631bb7d5
    replicas: 1

node:
  enabled: true

  image: registry.git.rwth-aachen.de/acs/public/villas/node:latest

  uuid: null # Autogenerate UUID
  logLevel: info

  portOffset: 12000
  portCount: 10

  persistence:
    enabled: true
    size: 1Gi

  extraConfig:
    hugepages: 0

    http:
      htdocs: /usr/share/villas/node/web
      port: 8080

    logging:
      level: info

    nodes:
      sig:
        type: signal
        signal: mixed
        values: 5
        rate: 20
      lo:
        type: loopback

      ws_sig:
        type: websocket
        in:
          signals: []
      ws_lo:
        type: websocket
        in:
          signals:
          - name: Loopback
            type: float

    paths:
    - in: sig
      out: ws_sig
    - in: ws_lo
      out: lo
    - in: lo
      out: ws_lo

  extraNodes: {}
  extraPaths: []

relay:
  enabled: true

  uuid: null # Autogenerate UUID
  logLevel: info
  loopback: false

  image: registry.git.rwth-aachen.de/acs/public/villas/node:latest

controller:
  enabled: true

  rbac:
    enabled: true

  uuid: null # Autogenerate UUID
  namespace: null # Use "{{ .Release.Namespace }}-controller"
  logLevel: info
  name: Kubernetes Controller

  image: registry.git.rwth-aachen.de/acs/public/villas/controller:latest

  extraComponents: []

  extraConfig:
    components: []

database:
  # Set to false for using an external broker
  # If so, provide the connection details in broker.external
  enabled: true

  # external:
  #   hostname: postgresql.postgresql
  #   name: villas
  #   username: villas
  #   password: XXXX

  postgresqlUsername: villas
  postgresqlDatabase: villas
  postgresqlPassword: changeme

broker:
  # Set to false for using an external broker
  # If so, provide the connection details in broker.external
  enabled: true

  # external:
  #   hostname: broker.villas-demo
  #   username: admin
  #   password: changeme

  extraPlugins: rabbitmq_mqtt

  service:
    extraPorts:
    - name: mqtt
      port: 1883
      targetPort: mqtt

  auth:
    username: villas
    # password: changeme
    # erlangCookie: Uy2RmPBj66F7fTZ8Bx66eKb1xOOoZTyv

s3:
  enabled: true

  bucket: villas-web
  region: default

  external:
    enabled: false

    access_key: changeme
    secret_key: changeme

    endpoint: minio.minio

    nossl: true
    pathstyle: true

  accessKey: changeme
  secretKey: changeme

  buckets:
  - name: villas-web
    policy: none
    purge: false

  resources:
    requests:
      # default is 4Gi which is to big for most dev machines...
      memory: 1Gi
