imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

storageClass: null

ingress:
  enabled: true

  host: localhost

  annotations: {}

  # Overwrite the ingress port if not 80 / 443
  port: null

  tls:
    enabled: false
    secretName: villas-tls

web:
  enabled: true

  mode: release
  title: VILLASweb
  sub_title: ""
  contact:
    name: Steffen Vogel
    mail: svogel2@eonerc.rwth-aachen.de

  metrics:
    enabled: true

  rancherURL: rancher.k8s.eonerc.rwth-aachen.de
  k8sCluster: local

  extraConfig: {}

  # Mapping of external groups to list of scenario IDs
  groups:
    project@slew-fantasygroup:
    - scenario: 1
      duplicate: false
    - scenario: 2
    - scenario: 5

  auth:
    logout_url: /oauth2/sign_out?rd=https%3A%2F%2Fjupyter.k8s.eonerc.rwth-aachen.de%2Fhub%2Flogout

    admin:
      username: admin
      mail: admin@example.com
      # password: changeme

    external:
      enabled: false

      client_id: villas
      client_secret: "Ho0Zeilahxoh3Cae0ao9rieHooL1oonah0nash6aiNae7phaiceeCoo9Eesh6tei"

      cookie_secret: "ohth8iin6QuiequeGu5tiengizip4eid"

      # email_domains:
      # - "*"
      # allowed_groups:
      # - student

      provider: jupyterhub
      provider_name: JupyterHub

      login_url: https://jupyter.k8s.eonerc.rwth-aachen.de/hub/api/oauth2/authorize
      redeem_url: https://jupyter.k8s.eonerc.rwth-aachen.de/hub/api/oauth2/token
      validate_url: https://jupyter.k8s.eonerc.rwth-aachen.de/hub/api/oauth2/validate

  backend:
    enabled: true

    image: registry.git.rwth-aachen.de/acs/public/villas/web-backend-go:latest

  frontend:
    enabled: true

    image: registry.git.rwth-aachen.de/acs/public/villas/web:latest
    replicas: 2

proxy:
#  image: quay.io/oauth2-proxy/oauth2-proxy
  image: stv0g/oauth2-proxy

  extraEnv:
    OAUTH2_PROXY_JUPYTERHUB_URL: https://jupyter.k8s.eonerc.rwth-aachen.de

node:
  enabled: true

  image: registry.git.rwth-aachen.de/acs/public/villas/node:latest

  uuid: null # Autogenerate UUID

  # One of: trace, debug, info, warning, error, critical, off
  logLevel: info

  portOffset: 12000
  portCount: 10

  persistence:
    enabled: true
    size: 1Gi

  extraConfig:
    hugepages: 0

    http:
      port: 8080

    logging:
      level: info

    nodes:
      sig:
        type: signal
        signal: mixed
        values: 5
        rate: 20
      lo:
        type: loopback

      ws_sig:
        type: websocket
        in:
          signals: []
          hooks:
          - type: stats
            buckets: 25
            warmup: 100
            verbose: true
            format: json
      ws_lo:
        type: websocket
        in:
          signals:
          - name: Loopback
            type: float

          hooks:
          - type: stats
            buckets: 25
            warmup: 100
            verbose: true
            format: json
    paths:
    - in: sig
      out: ws_sig
    - in: ws_lo
      out: lo
    - in: lo
      out: ws_lo

  extraNodes: {}
  extraPaths: []

relay:
  enabled: true

  uuid: null # Autogenerate UUID

  # One of: trace, debug, info, warning, error, critical, off
  logLevel: info

  loopback: false

  image: registry.git.rwth-aachen.de/acs/public/villas/node:latest

controller:
  enabled: true

  uuid: null # Autogenerate UUID

  # One of critical, error, warning, info, debug
  logLevel: info

  image: registry.git.rwth-aachen.de/acs/public/villas/controller:latest

  kubernetes:
    enabled: true

    rbac:
      enabled: true

    namespace: null # Default to "{{ .Release.Namespace }}-controller"

    uuid: null # Autogenerate UUID
    rancherURL: https://rancher.k8s.eonerc.rwth-aachen.de
    clusterName: local

  extraComponents: []
  extraConfig: {}

database:
  # Set to false for using an external broker
  # If so, provide the connection details in broker.external
  enabled: true

  # external:
  #   hostname: postgresql.postgresql
  #   name: villas
  #   username: villas
  #   password: XXXX

  postgresqlUsername: villas
  postgresqlDatabase: villas
  postgresqlPassword: changeme

  # Improve compatability with older systems
  shmVolume:
    enabled: false

  postgresqlExtendedConf:
    hugePages: "off"

broker:
  # Set to false for using an external broker
  # If so, provide the connection details in broker.external
  enabled: true

  # external:
  #   hostname: broker.villas-demo
  #   username: admin
  #   password: changeme

  extraPlugins: rabbitmq_mqtt

  extraConfiguration: |
    management.path_prefix = /broker

  service:
    extraPorts:
    - name: mqtt
      port: 1883
      targetPort: mqtt

  auth:
    username: villas
    # password: changeme
    # erlangCookie: Uy2RmPBj66F7fTZ8Bx66eKb1xOOoZTyv

s3:
  enabled: true

  bucket: villas-web
  region: default

  external:
    enabled: false

    access_key: changeme
    secret_key: changeme

    endpoint: minio.minio

    nossl: true
    pathstyle: true

  accessKey: changeme
  secretKey: changeme

  buckets:
  - name: villas-web
    policy: none
    purge: false

  resources:
    requests:
      # default is 4Gi which is to big for most dev machines...
      memory: 1Gi

  environment:
    MINIO_REGION_NAME: default
    MINIO_BROWSER: off


pintura:
  enabled: true

  replicas: 1

  image: sogno/pintura:latest
