# Default values for villas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

storageClass: rook-ceph-block

ingress:
  enabled: true

  host: villas.k8s.eonerc.rwth-aachen.de

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    eonerc.rwth-aachen.de/description: VILLASweb
    eonerc.rwth-aachen.de/link: https://git.rwth-aachen.de/acs/public/villas/web

  tls:
    enabled: true
    secretName: letsencrypt-prod-villas-demo

web:
  enabled: true

  backend:
    image: registry.git.rwth-aachen.de/acs/public/villas/web-backend-go:33eab641

  frontend:
    image: registry.git.rwth-aachen.de/acs/public/villas/web:723af74e
    replicas: 2

node:
  enabled: true

  image: registry.git.rwth-aachen.de/acs/public/villas/node:latest

  portOffset: 12000
  portCount: 10

  persistence:
    enabled: true
    size: 1Gi

  config:
    hugepages: 0

    http:
      htdocs: /usr/share/villas/node/web
      port: 8080

    logging:
      level: info

    nodes:
      sig:
        type: signal
        signal: mixed
        values: 5
        rate: 20
      lo:
        type: loopback
      ws_sig:
        type: websocket
      ws_lo:
        type: websocket

    paths:
    - in: sig
      out: ws_sig
    - in: ws_lo
      out: lo
    - in: lo
      out: ws_lo

  extraNodes: {}
  extraPaths: []

relay:
  enabled: true

  image: registry.git.rwth-aachen.de/acs/public/villas/node:latest

controller:
  enabled: true

  image: registry.git.rwth-aachen.de/acs/public/villas/controller:latest

  extraComponents: []

  config:
    components:
    - name: Kubernetes Controller
      category: controller
      type: kubernetes
      namespace : villas-controller

database:
  enabled: true

  postgresqlUsername: villas
  postgresqlPassword: kasdhjflkasd
  postgresqlDatabase: villas

broker:
  enabled: true

  extraPlugins: rabbitmq_mqtt

  service:
    extraPorts:
    - name: mqtt
      port: 1883
      targetPort: mqtt

  auth:
    username: user
    password: x123

    erlangCookie: YBog1yYYsL1PNuQBLFgAN3a2oc2a0Bej

