# Default values for villas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

storageClass: rook-ceph-block

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
	enabled: true

web:
	enabled: true

database:
	enabled: true

node:
	enabled: true

relay:
	enabled: true
