apiVersion: v1
kind: Service
metadata:
  name: {{ include "fiware-orion.broker.fullname" . }}
  labels:
    {{- include "fiware-orion.broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.broker.service.type }}
  ports:
    - port: {{ .Values.broker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fiware-orion.broker.selectorLabels" . | nindent 4 }}
